auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /auth

application:
    resource: "@ApplicationBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api
