application_curso:
    resource: "@ApplicationBundle/Controller/CursoController.php"
    type:     annotation

application_ciclo_lectivo:
    resource: "@ApplicationBundle/Controller/CicloLectivoController.php"
    type:     annotation

api_api_user:
    resource: "@ApiBundle/Controller/ApiUserController.php"
    type:     annotation

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /auth

application:
    resource: "@ApplicationBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

logout:
    path: /logout
