application_alumno_examen:
    resource: "@ApplicationBundle/Controller/AlumnoExamenController.php"
    type:     annotation

application_examen:
    resource: "@ApplicationBundle/Controller/ExamenController.php"
    type:     annotation

api_api_user:
    resource: "@ApiBundle/Controller/ApiUserController.php"
    type:     annotation

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /auth

application:
    resource: "@ApplicationBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

logout:
    path: /logout
