# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AuthBundle\Entity\User: plaintext

    providers:
        administrators:
            entity: { class: AuthBundle:User, property:username }

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: login

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/clase, roles: ROLE_ADMIN }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/alumnos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }




    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
