<?php

namespace ApplicationBundle\Repository;

/**
 * AlumnoExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
