<?php

namespace ApplicationBundle\Repository;

/**
 * AnioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnioRepository extends \Doctrine\ORM\EntityRepository
{
}
