<?php

namespace ApplicationBundle\Repository;

/**
 * A¤oRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class A¤oRepository extends \Doctrine\ORM\EntityRepository
{
}
