<?php

namespace ApplicationBundle\Repository;

/**
 * BibliotecaAlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliotecaAlumnoRepository extends \Doctrine\ORM\EntityRepository
{
}
