<?php

namespace ApplicationBundle\Repository;

/**
 * BoletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletinRepository extends \Doctrine\ORM\EntityRepository
{
}
