<?php

namespace ApplicationBundle\Repository;

/**
 * CicloLectivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CicloLectivoRepository extends \Doctrine\ORM\EntityRepository
{
}
