<?php

namespace ApplicationBundle\Repository;

/**
 * Ciclo_lectivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ciclo_lectivoRepository extends \Doctrine\ORM\EntityRepository
{
}
