<?php

namespace ApplicationBundle\Repository;

/**
 * Clase_en_vivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Clase_en_vivoRepository extends \Doctrine\ORM\EntityRepository
{
}
