<?php

namespace ApplicationBundle\Repository;

/**
 * DiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaRepository extends \Doctrine\ORM\EntityRepository
{

    public function getHorarioByDiaAndMateria($dia,$materia){
        return ['materia'=>$dia->getHorarioDiaMateria()->getMateria(),
                'horario'=>$dia->getHorarioDiaMateria()->getHorario()];
    }

}
