<?php

namespace ApplicationBundle\Repository;

/**
 * HorarioDiaMateraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioDiaMateraRepository extends \Doctrine\ORM\EntityRepository
{
}
