<?php

namespace ApplicationBundle\Repository;

/**
 * Opcion_preguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Opcion_preguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
