<?php

namespace ApplicationBundle\Repository;

/**
 * PersonalDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalDocenteRepository extends \Doctrine\ORM\EntityRepository
{
}
