<?php

namespace ApplicationBundle\Repository;

/**
 * TipoNotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoNotaRepository extends \Doctrine\ORM\EntityRepository
{
}
