<?php

namespace ApplicationBundle\Repository;

/**
 * TipoAsistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAsistenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
