<?php

namespace TeachingClassBundle\Repository;

/**
 * AnonimoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnonimoRepository extends \Doctrine\ORM\EntityRepository
{
}
