<?php

namespace TeachingClassBundle\Repository;

/**
 * AuditoriaClaseDidacticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriaClaseDidacticaRepository extends \Doctrine\ORM\EntityRepository
{
}
