<?php

namespace TeachingClassBundle\Repository;

/**
 * ClaseDidacticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseDidacticaRepository extends \Doctrine\ORM\EntityRepository
{
}
