<?php

namespace TeachingClassBundle\Repository;

/**
 * TipoPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
