<?php

namespace AuthBundle\Repository;

/**
 * UserAlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAlumnoRepository extends \Doctrine\ORM\EntityRepository
{
}
