<?php

namespace AuthBundle\Repository;

/**
 * UserPersonalDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPersonalDocenteRepository extends \Doctrine\ORM\EntityRepository
{
}
